spring:  
  application:
    name: backend 
  jackson:
    property-naming-strategy: SNAKE_CASE  
  datasource:
    url: jdbc:postgresql://localhost:5432/odds_ecommerce
    username: kerich
    password: kerichfelix
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: kerich
      password: kerichfelix
server:
  port: 1010

# spring:
#   application:
#     name: backend
#   jackson:
#     property-naming-strategy: SNAKE_CASE
#   datasource:
#     url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require
#     username: postgres.ssnvhjkpaayshfivauxp
#     password: 8088861fF%ODDSSTORE
#     driver-class-name: org.postgresql.Driver
#     hikari:
#       minimum-idle: 5
#       maximum-pool-size: 20
#       idle-timeout: 30000
#       connection-timeout: 30000
#   jpa:
#     show-sql: true
#     hibernate:
#       ddl-auto: update
#       jdbc:
#         lob:
#           non_contextual_creation: true
# server:
#   port: 1010


